name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denvercoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCEY98zVls33dVkLik5hYN2g
          comment_tag_name: YOUTUBE
          card_width: 450
          max_videos: 2
          background_color: "#0d1117"
          title_color: "#ffffff"
          stats_color: "#dedede"
          theme: "dark"
