name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          playlist_id: UULF2WHjPDvbE6O328n17ZGcfg
          comment_tag_name: YOUTUBE-CARDS
          show_duration: true
